### ISSUE TITLE
Not able to install v0.0.52 - PIP errors

### ISSUE THREAD

**Issue by V4NDL0** [freemocap/freemocap#134]
Followed the instructions for b.0.0.52 update

The PIP install took hours and then failed. 

says  "pip is looking at multiple versions of...." / "this may take a while" - does this for imageo, decorator, moviespy, kiwisolver and cycler etc.

Also - 

"  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

When completed fails with following:

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Steve\anaconda3\lib\site-packages\pip_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\Steve\anaconda3\lib\site-packages\pip_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Users\Steve\anaconda3\lib\site-packages\pip_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Steve\anaconda3\lib\site-packages\pip_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Steve\anaconda3\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Steve\anaconda3\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 383, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000..

Anaconda now won't run ipython or Freemocap env - it was working OK for me with the previous Freemocap version - I was able to process video, but the Blender output didn't work.

**Comment by jonmatthis** [comment]
Just restart completely from scratch and see if that works:

0. Open an `Anaconda Prompt` terminal
1. Remove the broken anaconda environment. If it was called `freemocap-env`, use the command: `conda remove -n freemocap-
env --all`
then follow the standard instructions: 

1. make a new python environment - `conda create -n freemocap-env python=3.7`
2. activate that environment - `conda activaet freemocap-env`
3. install freemocap - `pip install freemocap`
4. start an ipython session with - `ipython`
5. `import freemocap`
6. `freemocap.RunMe(useBlender=True)`

see if that works

**Comment by V4NDL0** [comment]
It worked. Blender export is also working now. Thanks!
