### ISSUE TITLE
FreeMocap.exe fails to execute; recursion during loading of cv2

### ISSUE THREAD

**Issue by mprib** [freemocap/freemocap#231]
I'm attempting to follow the README.md instructions for the current main repo and hitting some roadblocks.

My System: Windows 10

Steps to reproduce:

1. Forked repo and cloned to PC. 

from admin  powershell in freemocap directory:

2. Installed Chocolatey
3. ran `choco install blender ffmpeg` with successful installations
4. created venv and activated from powershell with `.\env\Scripts\Activate.ps1`
5. confirmed python --version --> 3.9.0
6. installed packages with `pip install -r requirements.txt`

At this point, the README says "That's it! You're ready to run the freemocap application, and create your own digital skeletons", but I don't know if this means that I must generate the actual .exe to launch it or if I can just run some python module to launch it. 

So I move forward with the "Usage: For Developers" section and 

8. run `task setup` successfully
9. `task test` didn't run for me so I manually ran `python -m unittest discover` 
	- this flagged a number of module import issues (referencing scratch modules) that I manually updated

10. `python -m unittest src/tests/**/test_*` also did not run
11. Switch to git bash and activate env with `source env/Scripts/activate`
12. run  `python -m unittest src/tests/**/test_*`
13. test fails:

```
line 27, in test_write_on_video_writer
    vw = VideoRecorder("nothing", 100, 100, "nothing")
TypeError: __init__() takes 1 positional argument but 5 were given
```

14. updated the unit test to read `vw = VideoRecorder()` after looking back at it's definition
15. run  `python -m unittest src/tests/**/test_*` for git bash: 1 test ran OK.
16. run `task installer` from both powershell and git bash without success
17. run `./bin/installer.sh` from powershell and it produces dist\FreeMoCap.exe
18. run FreeMoCap.exe and receive the following error:

```
Traceback (most recent call last):
  File "src\gui\main\main.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "src\gui\main\main_window\main_window.py", line 21, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "src\core_processes\capture_volume_calibration\get_anipose_calibration_object.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "src\core_processes\capture_volume_calibration\anipose_camera_calibration\freemocap_anipose.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib\__init__.py", line 126, in import_module
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "cv2\__init__.py", line 76, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
```

So this is where I currently am. Any insight into how to get the current version running is much appreciated. *Thank you for the work you all are doing on this project! I think it is important and want to contribute!*

**Comment by mprib** [comment]
Saw the comment from Endurance regarding the current status of the project, so this is not actually relevant.
