### ISSUE TITLE
Prealpha no longer works due to missing files. Suggest Alpha gives feedback on buttons.

### ISSUE THREAD

**Issue by KaijuKoder** [freemocap/freemocap#302]
Thank you for your work on freemocap. Been experimenting with freemocap (and BlendARmocap) and found the following:

1. The freemocap prealpha no longer works due to Google moving some files in the later release of Mediapipe. Related? https://github.com/google/mediapipe/issues/3698 https://github.com/google/mediapipe/issues/3643

```
│ C:\ProgramData\Anaconda3\envs\freemocap-env6\lib\urllib\request.py:649 in http_error_default     │
│                                                                                                  │
│    646                                                                                           │
│    647 class HTTPDefaultErrorHandler(BaseHandler):                                               │
│    648 │   def http_error_default(self, req, fp, code, msg, hdrs):                               │
│   649 │   │   raise HTTPError(req.full_url, code, msg, hdrs, fp)                                │
│    650                                                                                           │
│    651 class HTTPRedirectHandler(BaseHandler):                                                   │
│    652 │   # maximum number of redirections to any single URL                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
HTTPError: HTTP Error 404: Not Found
```

Found you can download them manually from here, though wasn't easy to work out. Would be nice if the prealpha was changed to download the correct file automatically: https://google.github.io/mediapipe/solutions/models.html

2. Found various dependency issues too, but using pip to uninstall and reinstall kiwisolver and matplotlib got it working. If anyone else gets stuck on these, try this. It is apparently the standard fix when these break.

3. Tried the alpha version, but had some issues. Retrying now. Suggestion: The buttons don't change when you click on them, so it isn't clear they are doing anything unless you foreground the Anaconda console window you started it from. Would be good to give feedback by disabling button once you click on it, and re-enabling it when it's action completes.

**Comment by KaijuKoder** [comment]
Encountered various bugs running freemocap-prealpha and freemocap-alpha.

freemocap-prealpha seems more reliable, but now it's stuck, and freemocap-alpha I just couldn't get working at all.

**1.** Today when I tested it, it ran first time, but on the following runs it kept giving this error **"IndexError: list index out of range"** as soon as I did fmc.RunMe() and successfully recorded the videos. Besides first time, couldn't run past this. 

```
 │   183 │   │   │   a_sync_vid_path = list(sesh.syncedVidPath.glob('*.mp4'))                       │
│ ❱ 184 │   │   │   temp_cap =   cv2.VideoCapture(str(a_sync_vid_path[0]))           
 │   185 │   │      sesh.numFrames = temp_cap.get(cv2.CAP_PROP_FRAME_COUNT)                        │
│   186 │   │      temp_cap.release()                                                             │
│   187                                                                                            │
IndexError: list index out of range
```

**2. freemocap-prealpha again. Found if I didn't run it in Administrator mode, got this:**

```
│                                                                                                  │
│ C:\ProgramData\Anaconda3\envs\freemocap-env6\lib\pathlib.py:1063 in _opener                      │
│                                                                                                  
│   1060 │                                                                                         │
│   1061 │   def _opener(self, name, flags, mode=0o666):                                           │
│   1062 │   │   # A stub for the opener argument to built-in open()                               │
│ self._accessor.open(self, flags, mode)                                     │
│   1064 │                                                                                         │
   1065 │   def _raw_open(self, flags, mode=0o777):                                               │
│   1066    │   """                                                                               │
nssionError: [Errno 13] Permission denied:
'C:\\ProgramData\\Anaconda3\\envs\\freemocap-env6\\lib\\site-packages\\freemocap\\fmc_startup\\user_preferences.yaml'
```

3. Freemocap-alpha: Tried many times but kept running into errors.

**3a) Index out of range error.**
```
 [   DEBUG] [traitlets] [_handle_execute_reply():452] [PID:14868 TID:10836] execute_reply: {'status': 'ok', 'execution_count': 3, 'user_expressions': {}, 'payload': []}
    charuco_frames = [f["framenum"][1] for f in all_rows[0]]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guest\freemocap\src\gui\main\workers\anipose_calibration_thread_worker.py", line 55, in run
    raise Exception
Exception
```

**3b) I tried using different combinations of cameras on different ports (combinations of 2 or 3 cameras, but keep getting this):** 
```
 File "C:\Users\guest\freemocap\src\gui\main\workers\mediapipe_2d_detection_thread_worker.py", line 31, in run
    mediapipe_skeleton_detector.process_folder_full_of_videos(
  File "C:\Users\guest\freemocap\src\core_processes\mediapipe_stuff\mediapipe_skeleton_detector.py", line 267, in process_folder_full_of_videos
    number_of_frames = all_cameras_data2d_list[0].shape[0]
IndexError: list index out of range

```
**3c) Finally, out of memory. The PC I'm using has 32Gb and this should be enough, but it did use 96% of memory!** 

```
 [    INFO] [src.cameras.capture.opencv_camera.camera_stream_thread_handler] [_start_frame_loop():83] [PID:14868 TID:13532] Frame loop thread exited.
meceback (most recent call last):
  File "C:\Users\guest\freemocap\src\cameras\capture\opencv_camera\opencv_camera.py", line 220, in get_next_frame
    success, image = self._opencv_video_capture_object.retrieve()
  File "C:\Users\guest\freemocap\src\cameras\capture\opencv_camera\opencv_camera.py", line 220, in get_next_frame
    success, image = self._opencv_video_capture_object.retrieve()
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 2764800 bytes in function 'cv::OutOfMemoryError'

cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 2764800 bytes in function 'cv::OutOfMemoryError'

```

**Comment by aaroncherian** [comment]
Hey there - 

First off, appreciate all the trouble you went through to try and troubleshoot the source of the problems. While we're not releasing more updates for the pre-alpha, there should be an alpha update coming relatively soon that will hopefully be a little more reliable and have UI updates that include button feedback.

I can't troubleshoot much on the alpha version, that's more of @jonmatthis's domain, but as for the pre-alpha:

1) We pinned the mediapipe version when the pre-alpha was first released, but if that version is deprecated to the point of being unusable you can try running `pip install mediapipe -U`, which should upgrade the mediapipe version in your environment, and I don't believe there will be compatibility issues between the newest mediapipe version and the pre-alpha. 

I can try to help out with the pre-alpha error you're running into - for that session, in the `SyncedVideos` folder, did it successfully record videos that you can play into that folder?

**Comment by KaijuKoder** [comment]
1. Thanks for the advice on  `pip install mediapipe -U`. Perhaps you can put add this to "Pre-Alpha Installation Instructions" on your frontpage since those commands no longer work without it. 

2. I used a debugger to find out the SyncedVideos problem. I was clicking on the 'X' button to close the runcams.py `proceed = timesync.proceedGUI()` summary window. runcams.py then skipped the VideoTrim() code so step 2 wasn't fully completed, but the code proceeded to step 3 anyway, where it looked for the SyncedVideos, and not finding them, threw that Python error. In effect, it was proceeding to stage 3 before stage 2 was complete.

Some suggestions: It might help for the software to write a state file recording what stages have been completed so far, that way if a step is missed or doesn't successfully complete, easier to detect. Personally I found the treatment of the 'X' button confusing. On that window, it's treated as a quit, but on the next window, it seems you are expected to hit the 'X' button. Confusing. Even if you do quit, shouldn't proceed to the next step. Perhaps the alpha will be different.

Anyway, when I hit 'proceed' instead of 'X' at the first window, and 'X' on the second window, it works.

3. Thanks for your work and your fast reply. Apart from the above, the prealpha is quite good. I'll wait for the new Alpha to appear.

**Comment by lha4432** [comment]
> Thank you for your work on freemocap. Been experimenting with freemocap (and BlendARmocap) and found the following:
> 
> 1. The freemocap prealpha no longer works due to Google moving some files in the later release of Mediapipe. Related? [Backward compatibility for downloading tflite files from the repository google/mediapipe#3698](https://github.com/google/mediapipe/issues/3698) [pose_landmark_heavy.tflite not copied to mediapipe installation google/mediapipe#3643](https://github.com/google/mediapipe/issues/3643)
> 
> ```
> │ C:\ProgramData\Anaconda3\envs\freemocap-env6\lib\urllib\request.py:649 in http_error_default     │
> │                                                                                                  │
> │    646                                                                                           │
> │    647 class HTTPDefaultErrorHandler(BaseHandler):                                               │
> │    648 │   def http_error_default(self, req, fp, code, msg, hdrs):                               │
> │   649 │   │   raise HTTPError(req.full_url, code, msg, hdrs, fp)                                │
> │    650                                                                                           │
> │    651 class HTTPRedirectHandler(BaseHandler):                                                   │
> │    652 │   # maximum number of redirections to any single URL                                    │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> HTTPError: HTTP Error 404: Not Found
> ```
> 
> Found you can download them manually from here, though wasn't easy to work out. Would be nice if the prealpha was changed to download the correct file automatically: https://google.github.io/mediapipe/solutions/models.html
> 
> 2. Found various dependency issues too, but using pip to uninstall and reinstall kiwisolver and matplotlib got it working. If anyone else gets stuck on these, try this. Seems it is the standard fix when these break.
> 3. Tried the alpha version, but had some issues. Retrying now. Suggestion: The buttons don't change when you click on them, so it isn't clear they are doing anything unless you foreground the Anaconda console window you started it from. Would be good to give feedback by disabling button once you click on it, and re-enabling it when it's action completes. Would also be good if it indicated what stage you are at (so you know which button to press next).

I'm running into the same error. I'm attempting to resolve the issue similar to how you explained, but it's a bit unclear what you mean. After downloading the mediapipe pose_landmark_heavy.tflite file, but what do I do after that? You then mention that you uninstalled and reinstalled kiwisolver and matplotlib. Were those just pip uninstalls and pip installs? Or was there something else you did?

**Comment by KaijuKoder** [comment]
Hi @lha4432,

1. Where `pose_landmark_heavy.tflite `goes will depend on your system. If you look through the messages printed on the console you'll see it's intended location in there. On my system it is in `C:\ProgramData\Anaconda3\envs\freemocap-env\Lib\site-packages\mediapipe\modules\pose_landmark\pose_landmark_heavy.tflite` so I downloaded it manually and put it there.

@aaroncherian also suggested you could do `pip install mediapipe -U` instead, though having got it working and not wanting to break it now, I didn't test it. If you try it and it does work, please report that here so they can modify the instructions on the https://freemocap.org/ frontpage.

2. Python's versioning system is very messy. Although virtual environments like conda try to fix that, you can still get dependency conflicts. If the install reports conflicts with kiwisolver or matplotlib, try using pip to uninstall and reinstall them, but if you don't get those errors, you don't need to do anything.

**Comment by lha4432** [comment]
Thank you! Downloading the `pose_landmark_heavy.tflite' file fixed everything on my part. Your instructions were very helpful. 

Also something to note: I attempted to do `pip install mediapipe -U` prior to attempting downloading the `pose_landmark_heavy.tflite' file but it did not work. I also attempted uninstalling and reinstalling the mediapipe library but to no avail.

**Comment by KaijuKoder** [comment]
Thanks for the feedback, @lha4432. I also tried `pip install mediapipe -U` and it didn't work for me either.

@aaroncherian and @jonmatthis, could you please update the "Pre-Alpha Installation Instructions" on the first page https://freemocap.org/ to include an additional step? (between `pip install freemocap==0.0.54` and `ipython`)?

`Download the file pose_landmark_heavy.tflite from https://google.github.io/mediapipe/solutions/models.html and store it as e.g. C:\ProgramData\Anaconda3\envs\freemocap-env\Lib\site-packages\mediapipe\modules\pose_landmark\pose_landmark_heavy.tflite
`

It takes a lot of time for a user to figure this out, and I'm worried that people who come to try freemocap will be turned away by this. Until the alpha is working properly, this will let people use the prealpha which already quite good... once you get it working!
