### ISSUE TITLE
"OSError: [WinError 6] The handle is invalid" when calibrating prerecorded videos on Windows 11

### ISSUE THREAD

**Issue by noadanimation** [freemocap/freemocap#378]
After clicking "Calibrate from Videos" I get this error using a Windows 11 PC. Calibrating the same videos was successful on a machine running Windows 10.

[2023-04-28 09:21:26.0728] [   ERROR] [freemocap.gui.qt.workers.anipose_calibration_thread_worker] [run():65] [PID:11036 TID:32008] [WinError 6] The handle is invalid
Traceback (most recent call last):
  File "C:\Users\Dan\freemocap\freemocap\gui\qt\workers\anipose_calibration_thread_worker.py", line 53, in run
    run_anipose_capture_volume_calibration(
  File "C:\Users\Dan\freemocap\freemocap\core_processes\capture_volume_calibration\run_anipose_capture_volume_calibration.py", line 30, in run_anipose_capture_volume_calibration
    anipose_camera_calibrator.calibrate_camera_capture_volume(pin_camera_0_to_origin=pin_camera_0_to_origin)
  File "C:\Users\Dan\freemocap\freemocap\core_processes\capture_volume_calibration\anipose_camera_calibration\anipose_camera_calibrator.py", line 76, in calibrate_camera_capture_volume
    (error, charuco_frame_data, charuco_frame_numbers,) = self._anipose_camera_group_object.calibrate_videos(
  File "C:\Users\Dan\freemocap\freemocap\core_processes\capture_volume_calibration\anipose_camera_calibration\freemocap_anipose.py", line 1685, in calibrate_videos
    all_rows = self.get_rows_videos(videos, board, verbose=verbose)
  File "C:\Users\Dan\freemocap\freemocap\core_processes\capture_volume_calibration\anipose_camera_calibration\freemocap_anipose.py", line 1657, in get_rows_videos
    rows = board.detect_video(vidname, prefix=vnum, progress=verbose)
  File "C:\Users\Dan\anaconda3\envs\freemocap-env\lib\site-packages\aniposelib\boards.py", line 319, in detect_video
    it = trange(length, ncols=70)
  File "C:\Users\Dan\anaconda3\envs\freemocap-env\lib\site-packages\tqdm\std.py", line 1521, in trange
    return tqdm(range(*args), **kwargs)
  File "C:\Users\Dan\anaconda3\envs\freemocap-env\lib\site-packages\tqdm\std.py", line 1095, in __init__
    self.refresh(lock_args=self.lock_args)
  File "C:\Users\Dan\anaconda3\envs\freemocap-env\lib\site-packages\tqdm\std.py", line 1344, in refresh
    self.display()
  File "C:\Users\Dan\anaconda3\envs\freemocap-env\lib\site-packages\tqdm\std.py", line 1492, in display
    self.sp(self.__str__() if msg is None else msg)
  File "C:\Users\Dan\anaconda3\envs\freemocap-env\lib\site-packages\tqdm\std.py", line 347, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "C:\Users\Dan\anaconda3\envs\freemocap-env\lib\site-packages\tqdm\std.py", line 340, in fp_write
    fp.write(str(s))
  File "C:\Users\Dan\anaconda3\envs\freemocap-env\lib\site-packages\tqdm\utils.py", line 127, in inner
    return func(*args, **kwargs)
OSError: [WinError 6] The handle is invalid
[2023-04-28 09:21:26.0732] [    INFO] [freemocap.gui.qt.workers.anipose_calibration_thread_worker] [run():70] [PID:11036 TID:32008] Anipose Calibration Complete

**Comment by philipqueen** [comment]
Thanks for filing the issue, we've had another user having the same issue - this error on Windows 11 but working on Windows 10. This is something we'll have to test more on our end.
