### ISSUE TITLE
Errors when closing the LoggingQueueListener

### ISSUE THREAD

**Issue by philipqueen** [freemocap/freemocap#461]
On closing the GUI, errors like the one below are showing up. I say errors, because a few different errors can pop up depending on when in the event loop the kill event occurs. This same error was being thrown earlier, it just wasn't logged until the flake8 adoption encouraged us to log all of our error messages. 

It is good to keep logging the error messages, in case there are ever legitimate errors happening in the LoggingQueueListener. However, since this makes the terminal output always end in an error, it would be nice to have a fix for it, as I anticipate it will throw some users off.

```[2023-07-31 10:34:21.0986] [    INFO] [freemocap.gui.qt.freemocap_main] [qt_gui_main():48] [PID:82057 TID:4341056896] `main` exited with error code: 0
Thank you for using freemocap 💀 ❤ ✨
[2023-07-31 10:34:21.0987] [   ERROR] [freemocap.gui.qt.widgets.log_view_widget] [run():52] [PID:82057 TID:6134001664] [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/Users/philipqueen/miniconda3/envs/fmc_pip/lib/python3.9/site-packages/freemocap/gui/qt/widgets/log_view_widget.py", line 45, in run
    record = self._logging_queue.get(block=True)
  File "/Users/philipqueen/miniconda3/envs/fmc_pip/lib/python3.9/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/Users/philipqueen/miniconda3/envs/fmc_pip/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/philipqueen/miniconda3/envs/fmc_pip/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/philipqueen/miniconda3/envs/fmc_pip/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
OSError: [Errno 9] Bad file descriptor
[2023-07-31 10:34:21.0989] [    INFO] [freemocap.gui.qt.widgets.log_view_widget] [close():56] [PID:82057 TID:6134001664] Closing LoggingQueueListener thread
```

**Comment by philipqueen** [comment]
I've tried only logging the exception if `self._exit_event.is_set()` is False, but unfortunately it seems the exception is logged before the `close()` function is called, so that solution doesn't work
