### ISSUE TITLE
GUI Not Starting - DLL Load Failed Error

### ISSUE THREAD

**Issue by pishabh625** [freemocap/freemocap#505]
**Issue Report: GUI Not Starting - DLL Load Failed Error**

**Summary:**
The graphical user interface (GUI) fails to start, displaying a DLL Load Failed error.

**Steps to Reproduce:**
1. Create and activate a virtual environment using [`venv`](https://docs.python.org/3/library/venv.html).
2. Install the `freemocap` package by running:
    ```bash
    pip install freemocap
    ```
3. Launch the application:
    ```bash
    freemocap
    ```

**Expected Result:**
A functional GUI should appear as illustrated in the image [here](https://github.com/freemocap/freemocap/assets/82377845/83c489b1-514b-48e9-8efa-de35ef8c8aaf).

**Actual Result:**
An ImportError is encountered with the following traceback:

   ```plaintext
  Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prish\Downloads\Documents\FreeMoCap\env\Scripts\freemocap.exe\__main__.py", line 4, in <module>
    from pathlib import Path
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prish\Downloads\Documents\FreeMoCap\env\Lib\site-packages\freemocap\__init__.py", line 13, in <module>
    from freemocap.system.logging.configure_logging import configure_logging, LogLevel
  File "C:\Users\prish\Downloads\Documents\FreeMoCap\env\Lib\site-packages\freemocap\system\logging\configure_logging.py", line 7, in <module>
    from skellycam.system.environment.default_paths import get_log_file_path
  File "C:\Users\prish\Downloads\Documents\FreeMoCap\env\Lib\site-packages\skellycam\__init__.py", line 32, in <module>
    from skellycam.gui.qt.widgets.skelly_cam_config_parameter_tree_widget import SkellyCamParameterTreeWidget
  File "C:\Users\prish\Downloads\Documents\FreeMoCap\env\Lib\site-packages\skellycam\gui\qt\widgets\skelly_cam_config_parameter_tree_widget.py", line 5, in <module>
    from PyQt6.QtCore import pyqtSignal
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
   ```

What I Have Tried:
- Uninstalled Python 3.11.6 and reinstalled.
- Switched Python versions from 3.11.6 to 3.9.

_The issue persists despite these attempted solutions._

Environment:
Python Version: 3.11.6

Additional Information:
The error is linked to the import of QtCore from PyQt6 in the skelly_cam_config_parameter_tree_widget.py file.

I appreciate your prompt attention to this matter, and I'm open to providing any further details if needed.

**Comment by gerroon** [comment]
I have the same issue on Win 11 Python 3.10

```
freemocap
adding base_package_path: C:\venv\lib\site-packages\skellycam : to sys.path
Setting up skellycam logging C:\venv\lib\site-packages\skellycam\system\log_config\logsetup.py
[2023-12-02 20:43:00.0696] [    INFO] [skellycam.system.log_config.logsetup] [configure_logging():39] [PID:12904 TID:39548] Added logging handlers: [<StreamHandler <stdout> (DEBUG)>, <FileHandler C:\Users\kk\skelly-cam-recordings\logs_info_and_settings\logs\log_2023-12-02T20_43_00ms693_gmt-6.log (DEBUG)>]
[2023-12-02 20:43:00.0696] [    INFO] [skellycam] [<module>():27] [PID:12904 TID:39548] Initializing skellycam package, version: v2023.09.1086, from file: C:\venv\lib\site-packages\skellycam\__init__.py
Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\venv\Scripts\freemocap.exe\__main__.py", line 4, in <module>
    from pathlib import Path
  File "C:\freemocap\freemocap\__init__.py", line 13, in <module>
    from freemocap.system.logging.configure_logging import configure_logging, LogLevel
  File "C:\freemocap\freemocap\system\logging\configure_logging.py", line 7, in <module>
    from skellycam.system.environment.default_paths import get_log_file_path
  File "C:\venv\lib\site-packages\skellycam\__init__.py", line 32, in <module>
    from skellycam.gui.qt.widgets.skelly_cam_config_parameter_tree_widget import SkellyCamParameterTreeWidget
  File "C:\venv\lib\site-packages\skellycam\gui\qt\widgets\skelly_cam_config_parameter_tree_widget.py", line 5, in <module>
    from PyQt6.QtCore import pyqtSignal
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.

```

**Comment by pishabh625** [comment]
**Steps to Resolve the Issue:**

1. **🧹 Cleaned Up PyQt Packages:**
   - Removed all PyQt packages using the following commands:
     ```bash
     python -m pip list
     pip uninstall -y PyQt6 pyqt6-plugins PyQt6-Qt6 PyQt6-sip pyqt6-tools qt6-applications qt6-tools 
     pip uninstall pyqt5 pyqt5-sip pyqt5-qt5
     ```
   - Removal using.
   ![Cleaned Up PyQt Packages](https://github.com/freemocap/freemocap/assets/82377845/72850381-ab37-4cac-b382-1fbb8a7b74af)

2. **🔍 Checked for Remaining PyQt Packages:**
   - Ensured there were no lingering PyQt packages using `python -m pip list`.
   ![No Remaining PyQt Packages](https://github.com/freemocap/freemocap/assets/82377845/e8b9ca5f-0fef-4091-acb5-a5ceacff3141)

3. **🔄 Reinstalled PyQt6:**
   - Reinstalled PyQt6 using `python -m pip install pyqt6`.
   ![Reinstalled PyQt6](https://github.com/freemocap/freemocap/assets/82377845/ee8dae43-e54d-48aa-95c1-3e7db4d8344d)

4. **🔄 Reinstalled Freemocap:**
   - Uninstalled Freemocap and purged the pip cache using:
     ```bash
     pip uninstall freemocap
     pip cache purge
     ```
   ![Reinstalled Freemocap](https://github.com/freemocap/freemocap/assets/82377845/e38f50b7-75b5-4ab2-955b-d1945b2a3b54)
   - Reinstalled Freemocap using:
     ```bash
     pip install freemocap
     ```
   ![Reinstalled Freemocap](https://github.com/freemocap/freemocap/assets/82377845/cec61561-1a64-4bc9-8e11-006c5e2431b4)

5. **▶️ Launched Freemocap GUI:**
   - Successfully launched the GUI without any errors using the command `freemocap`.
   ![Launched Freemocap GUI](https://github.com/freemocap/freemocap/assets/82377845/417a8a95-03fe-4310-a2a8-ba0e5d3c11d4)

The issue has been resolved! 🚀 I might have taken a few extra steps, but the GUI is up and running smoothly. If you have any insights on which specific step solved the problem, I'm all ears! 🤔 Thanks again for your assistance! 🎉
-->
