### ISSUE TITLE
QThread: Destroyed while thread is still running

### ISSUE THREAD

**Issue by 031515a** [freemocap/freemocap#518]
i cant using that software to this error:

adding base_package_path: C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellycam : to sys.path
Setting up skellycam logging C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellycam\system\log_config\logsetup.py
[2023-12-24 16:21:27.0790] [    INFO] [skellycam.system.log_config.logsetup] [configure_logging():39] [PID:9948 TID:16420] Added logging handlers: [<StreamHandler <stdout> (DEBUG)>, <FileHandler C:\Users\THY\skelly-cam-recordings\logs_info_and_settings\logs\log_2023-12-24T16_21_27ms790_gmt+3.log (DEBUG)>]
[2023-12-24 16:21:27.0790] [    INFO] [skellycam] [<module>():27] [PID:9948 TID:16420] Initializing skellycam package, version: v2023.12.1090, from file: C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellycam\__init__.py
[2023-12-24 16:21:28.0732] [    INFO] [skellycam] [configure():126] [PID:9948 TID:16420] Logging already configured
[2023-12-24 16:21:28.0733] [    INFO] [freemocap] [<module>():18] [PID:9948 TID:16420] Initializing freemocap package, version: v1.0.33, from file: C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\__init__.pyThank you for using skelly_viewer!
This is printing from: C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\skelly_viewer\__init__.py
Source code for this package is available at: https://github.com/freemocap/skelly_viewer/
[2023-12-24 16:21:29.0031] [    INFO] [skelly_viewer.config.logging_configuration] [configure_logging():43] [PID:9948 TID:16420] Logging already configured!
Thank you for using skellyforge!
This is printing from: C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellyforge\__init__.py
Source code for this package is available at: https://github.com/freemocap/skellyforge/
16:21:29 ::   Utilities   ::   INFO   :: Running DeFFcode Version: 0.2.5
adding base_package_path: C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages : to sys.path
[2023-12-24 16:21:29.0703] [    INFO] [skelly_synchronize.system.logging_configuration] [configure_logging():42] [PID:9948 TID:16420] Logging already configured!
2023-12-24 16:21:29,703 - skelly_synchronize.system.logging_configuration - INFO - Logging already configured!
[2023-12-24 16:21:29.0707] [    INFO] [freemocap.gui.qt.freemocap_main] [qt_gui_main():29] [PID:9948 TID:16420] Starting main...
2023-12-24 16:21:29,707 - freemocap.gui.qt.freemocap_main - INFO - Starting main...
[2023-12-24 16:21:29.0724] [    INFO] [freemocap.gui.qt.main_window.freemocap_main_window] [__init__():100] [PID:9948 TID:16420] Initializing FreeMoCap MainWindow
2023-12-24 16:21:29,724 - freemocap.gui.qt.main_window.freemocap_main_window - INFO - Initializing FreeMoCap MainWindow
[2023-12-24 16:21:29.0725] [    INFO] [freemocap.gui.qt.widgets.log_view_widget] [run():39] [PID:9948 TID:7728] Starting LoggingQueueListener thread
2023-12-24 16:21:29,725 - freemocap.gui.qt.widgets.log_view_widget - INFO - Starting LoggingQueueListener thread
qt.svg: Could not create image from "C:/Users/THY/AppData/Local/Programs/Python/Python311/Lib/site-packages/freemocap/assets/logo/16530232.png"
qt.svg: Could not create image from "C:/Users/THY/AppData/Local/Programs/Python/Python311/Lib/site-packages/freemocap/assets/logo/16530236.png"
qt.svg: Could not create image from "C:/Users/THY/AppData/Local/Programs/Python/Python311/Lib/site-packages/freemocap/assets/logo/16530232.png"
qt.svg: Could not create image from "C:/Users/THY/AppData/Local/Programs/Python/Python311/Lib/site-packages/freemocap/assets/logo/16530236.png"
[2023-12-24 16:21:29.0740] [    INFO] [freemocap.gui.qt.main_window.freemocap_main_window] [__init__():120] [PID:9948 TID:16420] Failed to find previous GUI settings, using default settings
2023-12-24 16:21:29,740 - freemocap.gui.qt.main_window.freemocap_main_window - INFO - Failed to find previous GUI settings, using default settings
[2023-12-24 16:21:29.0825] [    INFO] [freemocap.gui.qt.widgets.directory_view_widget] [__init__():21] [PID:9948 TID:16420] Creating QtDirectoryViewWidget
2023-12-24 16:21:29,825 - freemocap.gui.qt.widgets.directory_view_widget - INFO - Creating QtDirectoryViewWidget
[2023-12-24 16:21:29.0826] [    INFO] [freemocap.gui.qt.widgets.directory_view_widget] [set_folder_as_root():79] [PID:9948 TID:16420] Setting root folder to C:\Users\THY\freemocap_data
2023-12-24 16:21:29,826 - freemocap.gui.qt.widgets.directory_view_widget - INFO - Setting root folder to C:\Users\THY\freemocap_data
[2023-12-24 16:21:29.0832] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():63] [PID:9948 TID:16420] Collapsing other directories
[2023-12-24 16:21:29.0834] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():65] [PID:9948 TID:16420] Expanding directory at  path: C:\Users\THY\freemocap_data\recording_sessions
[2023-12-24 16:21:29.0834] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():73] [PID:9948 TID:16420] Expanding parent directory at  path: C:\Users\THY\freemocap_data
qt.svg: Could not create image from "C:/Users/THY/AppData/Local/Programs/Python/Python311/Lib/site-packages/freemocap/assets/logo/16530232.png"
qt.svg: Could not create image from "C:/Users/THY/AppData/Local/Programs/Python/Python311/Lib/site-packages/freemocap/assets/logo/16530236.png"
[2023-12-24 16:21:29.0852] [    INFO] [freemocap.gui.qt.widgets.home_widget] [_welcome_to_freemocap_title():170] [PID:9948 TID:16420] Creating `welcome to freemocap` layout
2023-12-24 16:21:29,852 - freemocap.gui.qt.widgets.home_widget - INFO - Creating `welcome to freemocap` layout
[2023-12-24 16:21:29.0855] [   DEBUG] [urllib3.connectionpool] [_new_conn():1052] [PID:9948 TID:16420] Starting new HTTPS connection (1): pypi.org:443
[2023-12-24 16:21:30.0061] [   DEBUG] [urllib3.connectionpool] [_make_request():546] [PID:9948 TID:16420] https://pypi.org:443 "GET /pypi/freemocap/json HTTP/1.1" 200 23624
[2023-12-24 16:21:30.0079] [   DEBUG] [urllib3.connectionpool] [_new_conn():1052] [PID:9948 TID:16420] Starting new HTTPS connection (1): pypi.org:443
[2023-12-24 16:21:30.0279] [   DEBUG] [urllib3.connectionpool] [_make_request():546] [PID:9948 TID:16420] https://pypi.org:443 "GET /pypi/freemocap/json HTTP/1.1" 200 23624
[2023-12-24 16:21:30.0300] [    INFO] [skellycam.gui.qt.skelly_cam_widget] [__init__():48] [PID:9948 TID:16420] Initializing QtMultiCameraViewerWidget with camera_ids: None
2023-12-24 16:21:30,300 - skellycam.gui.qt.skelly_cam_widget - INFO - Initializing QtMultiCameraViewerWidget with camera_ids: None
[2023-12-24 16:21:30.0301] [    INFO] [skellycam.gui.qt.workers.camera_group_thread_worker] [__init__():37] [PID:9948 TID:16420] Initializing camera group frame worker with camera ids: None
2023-12-24 16:21:30,301 - skellycam.gui.qt.workers.camera_group_thread_worker - INFO - Initializing camera group frame worker with camera ids: None
[2023-12-24 16:21:30.0302] [   DEBUG] [skellycam.gui.qt.widgets.skelly_cam_controller_widget] [connect_buttons_to_slots():132] [PID:9948 TID:16420] Connecting <PySide6.QtWidgets.QPushButton(0x21c3b9e3cf0) at 0x0000021C3D1D9240>.clicked to <bound method CamGroupThreadWorker.start_recording of <skellycam.gui.qt.workers.camera_group_thread_worker.CamGroupThreadWorker(0x21c3ba55480) at 0x0000021C3AFCAA40>>
[2023-12-24 16:21:30.0303] [   DEBUG] [skellycam.gui.qt.widgets.skelly_cam_controller_widget] [connect_buttons_to_slots():132] [PID:9948 TID:16420] Connecting <PySide6.QtWidgets.QPushButton(0x21c3b9e4070) at 0x0000021C3D1D9840>.clicked to <bound method CamGroupThreadWorker.stop_recording of <skellycam.gui.qt.workers.camera_group_thread_worker.CamGroupThreadWorker(0x21c3ba55480) at 0x0000021C3AFCAA40>>
[2023-12-24 16:21:30.0304] [   DEBUG] [freemocap.system.paths_and_filenames.file_and_folder_names] [default_session_name():114] [PID:9948 TID:16420] Creating default session name: session_2023-12-24_16_21_30
QLayout: Attempting to add QLayout "" to CameraControllerGroupBox "", which already has a layout
[2023-12-24 16:21:30.0314] [    INFO] [freemocap.gui.qt.widgets.central_tab_widget] [_create_welcome_tab():55] [PID:9948 TID:16420] Creating welcome tab
2023-12-24 16:21:30,314 - freemocap.gui.qt.widgets.central_tab_widget - INFO - Creating welcome tab
[2023-12-24 16:21:30.0325] [    INFO] [freemocap.gui.qt.widgets.central_tab_widget] [_create_skellycam_view_tab():59] [PID:9948 TID:16420] Creating skellycam view tab
2023-12-24 16:21:30,325 - freemocap.gui.qt.widgets.central_tab_widget - INFO - Creating skellycam view tab
[2023-12-24 16:21:30.0328] [    INFO] [freemocap.gui.qt.widgets.central_tab_widget] [_create_skelly_viewer_tab():83] [PID:9948 TID:16420] Creating export_data tab
2023-12-24 16:21:30,328 - freemocap.gui.qt.widgets.central_tab_widget - INFO - Creating export_data tab
[2023-12-24 16:21:30.0330] [    INFO] [freemocap.gui.qt.widgets.central_tab_widget] [_create_directory_view_tab():88] [PID:9948 TID:16420] Creating directory view tab
2023-12-24 16:21:30,330 - freemocap.gui.qt.widgets.central_tab_widget - INFO - Creating directory view tab
[2023-12-24 16:21:30.0333] [    INFO] [freemocap.gui.qt.widgets.central_tab_widget] [_create_active_recording_info_tab():92] [PID:9948 TID:16420] Creating active recording info tab
2023-12-24 16:21:30,333 - freemocap.gui.qt.widgets.central_tab_widget - INFO - Creating active recording info tab
[2023-12-24 16:21:30.0342] [    INFO] [freemocap.gui.qt.widgets.active_recording_widget] [set_active_recording():62] [PID:9948 TID:16420] Setting active recording to C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3
2023-12-24 16:21:30,342 - freemocap.gui.qt.widgets.active_recording_widget - INFO - Setting active recording to C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3
[2023-12-24 16:21:30.0342] [   DEBUG] [freemocap.gui.qt.widgets.active_recording_widget] [_update_file_watch_path():78] [PID:9948 TID:16420] Updating file watch path to: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3
[2023-12-24 16:21:30.0343] [   DEBUG] [freemocap.gui.qt.widgets.active_recording_widget] [set_active_recording():68] [PID:9948 TID:16420] Emitting `new_active_recording_selected_signal` for recording: recording_12_14_04_gmt+3
[2023-12-24 16:21:30.0343] [    INFO] [freemocap.gui.qt.main_window.freemocap_main_window] [_handle_new_active_recording_selected():367] [PID:9948 TID:16420] New active recording selected: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3
2023-12-24 16:21:30,343 - freemocap.gui.qt.main_window.freemocap_main_window - INFO - New active recording selected: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3
[2023-12-24 16:21:30.0373] [    INFO] [freemocap.data_layer.recording_models.recording_info_model] [get_number_of_mp4s_in_synched_videos_directory():238] [PID:9948 TID:16420] Number of `.mp4`'s in C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3\synchronized_videos: 1.0
2023-12-24 16:21:30,373 - freemocap.data_layer.recording_models.recording_info_model - INFO - Number of `.mp4`'s in C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3\synchronized_videos: 1.0[2023-12-24 16:21:30.0375] [    INFO] [freemocap.gui.qt.widgets.directory_view_widget] [set_folder_as_root():79] [PID:9948 TID:16420] Setting root folder to C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15
2023-12-24 16:21:30,375 - freemocap.gui.qt.widgets.directory_view_widget - INFO - Setting root folder to C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15
[2023-12-24 16:21:30.0376] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():63] [PID:9948 TID:16420] Collapsing other directories
[2023-12-24 16:21:30.0376] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():65] [PID:9948 TID:16420] Expanding directory at  path: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3\synchronized_videos
[2023-12-24 16:21:30.0377] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():73] [PID:9948 TID:16420] Expanding parent directory at  path: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3
[2023-12-24 16:21:30.0377] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():73] [PID:9948 TID:16420] Expanding parent directory at  path: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15
[2023-12-24 16:21:30.0378] [    INFO] [freemocap.gui.qt.widgets.active_recording_widget] [update_parameter_tree():74] [PID:9948 TID:16420] Updating Parameter Tree
2023-12-24 16:21:30,378 - freemocap.gui.qt.widgets.active_recording_widget - INFO - Updating Parameter Tree
[2023-12-24 16:21:30.0378] [   DEBUG] [freemocap.gui.qt.widgets.active_recording_widget] [setup_parameter_tree():110] [PID:9948 TID:16420] Setting up `ActiveRecordingTreeView` for recording: recording_12_14_04_gmt+3
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[2023-12-24 16:21:30.0482] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():63] [PID:9948 TID:16420] Collapsing other directories
[2023-12-24 16:21:30.0482] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():65] [PID:9948 TID:16420] Expanding directory at  path: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3\annotated_videos
[2023-12-24 16:21:30.0483] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():73] [PID:9948 TID:16420] Expanding parent directory at  path: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3
[2023-12-24 16:21:30.0484] [   DEBUG] [freemocap.gui.qt.widgets.directory_view_widget] [expand_directory_to_path():73] [PID:9948 TID:16420] Expanding parent directory at  path: C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15
[2023-12-24 16:21:30.0484] [   ERROR] [freemocap.gui.qt.main_window.freemocap_main_window] [_handle_new_active_recording_selected():395] [PID:9948 TID:16420] 'MainWindow' object has no attribute '_process_motion_capture_data_panel'
2023-12-24 16:21:30,484 - freemocap.gui.qt.main_window.freemocap_main_window - ERROR - 'MainWindow' object has no attribute '_process_motion_capture_data_panel'
[2023-12-24 16:21:30.0484] [    INFO] [freemocap.gui.qt.utilities.update_most_recent_recording_toml] [update_most_recent_recording_toml():16] [PID:9948 TID:16420] Saving most recent recording path C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3 to toml file: C:\Users\THY\freemocap_data\logs_info_and_settings\most_recent_recording.toml
2023-12-24 16:21:30,484 - freemocap.gui.qt.utilities.update_most_recent_recording_toml - INFO - Saving most recent recording path C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3 to toml file: C:\Users\THY\freemocap_data\logs_info_and_settings\most_recent_recording.toml
[2023-12-24 16:21:30.0511] [    INFO] [freemocap.data_layer.recording_models.recording_info_model] [get_number_of_mp4s_in_synched_videos_directory():238] [PID:9948 TID:16420] Number of `.mp4`'s in C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3\synchronized_videos: 1.0
2023-12-24 16:21:30,511 - freemocap.data_layer.recording_models.recording_info_model - INFO - Number of `.mp4`'s in C:\Users\THY\freemocap_data\recording_sessions\session_2023-12-23_12_08_15\recording_12_14_04_gmt+3\synchronized_videos: 1.0[2023-12-24 16:21:30.0513] [    INFO] [freemocap.data_layer.recording_models.recording_info_model] [check_calibration_toml_status():221] [PID:9948 TID:16420] No calibration file found with session name, checking for other calibration files in recording session
2023-12-24 16:21:30,513 - freemocap.data_layer.recording_models.recording_info_model - INFO - No calibration file found with session name, checking for other calibration files in recording session
[2023-12-24 16:21:30.0514] [    INFO] [freemocap.gui.qt.widgets.control_panel.calibration_control_panel] [update_calibration_toml_path():127] [PID:9948 TID:16420] Setting calibration TOML path: C:\Users\THY\freemocap_data\logs_info_and_settings\last_successful_calibration.toml
2023-12-24 16:21:30,514 - freemocap.gui.qt.widgets.control_panel.calibration_control_panel - INFO - Setting calibration TOML path: C:\Users\THY\freemocap_data\logs_info_and_settings\last_successful_calibration.toml
[2023-12-24 16:21:30.0514] [    INFO] [freemocap.gui.qt.widgets.control_panel.calibration_control_panel] [update_calibration_toml_path():127] [PID:9948 TID:16420] Setting calibration TOML path: C:\Users\THY\freemocap_data\logs_info_and_settings\last_successful_calibration.toml
2023-12-24 16:21:30,514 - freemocap.gui.qt.widgets.control_panel.calibration_control_panel - INFO - Setting calibration TOML path: C:\Users\THY\freemocap_data\logs_info_and_settings\last_successful_calibration.toml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Scripts\freemocap.exe\__main__.py", line 7, in <module>
    sys.path.insert(0, str(base_package_path))  # add parent directory to sys.path
                 ^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\__main__.py", line 24, in main
    qt_gui_main()
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\freemocap_main.py", line 38, in qt_gui_main
    freemocap_main_window = MainWindow(
                            ^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\main_window\freemocap_main_window.py", line 151, in __init__
    self._control_panel_widget = self._create_control_panel_widget(log_update=self._log_view_widget.add_log)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\main_window\freemocap_main_window.py", line 315, in _create_control_panel_widget
    parent=self, blender_executable_path=get_best_guess_of_blender_path()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\core_processes\export_data\blender_stuff\get_best_guess_of_blender_path.py", line 34, in get_best_guess_of_blender_path
    blender_exe_path = guess_blender_exe_path_from_path(base_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\core_processes\export_data\blender_stuff\get_best_guess_of_blender_path.py", line 19, in guess_blender_exe_path_from_path
    best_guess = blender_folder_paths[-1]
                 ~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
[2023-12-24 16:21:30.0607] [   ERROR] [freemocap.gui.qt.widgets.log_view_widget] [run():52] [PID:9948 TID:7728] [WinError 6] The handle is invalid
Traceback (most recent call last):
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\widgets\log_view_widget.py", line 42, in run
    if self._logging_queue.empty():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\queues.py", line 129, in empty
    return not self._poll()
               ^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\connection.py", line 256, in poll
    return self._poll(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\connection.py", line 329, in _poll
    return bool(wait([self], timeout))
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\connection.py", line 854, in wait
    ov, err = _winapi.ReadFile(fileno(), 0, True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
2023-12-24 16:21:30,607 - freemocap.gui.qt.widgets.log_view_widget - ERROR - [WinError 6] The handle is invalid
Traceback (most recent call last):
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\widgets\log_view_widget.py", line 42, in run
    if self._logging_queue.empty():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\queues.py", line 129, in empty
    return not self._poll()
               ^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\connection.py", line 256, in poll
    return self._poll(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\connection.py", line 329, in _poll
    return bool(wait([self], timeout))
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\connection.py", line 854, in wait
    ov, err = _winapi.ReadFile(fileno(), 0, True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
[2023-12-24 16:21:30.0610] [    INFO] [freemocap.gui.qt.widgets.log_view_widget] [close():56] [PID:9948 TID:7728] Closing LoggingQueueListener thread
2023-12-24 16:21:30,610 - freemocap.gui.qt.widgets.log_view_widget - INFO - Closing LoggingQueueListener thread
QThread: Destroyed while thread is still running

**Comment by philipqueen** [comment]
Hi @031515a, sorry you're having troubles!

It looks like the real error is happening while the software is trying to guess wher eBlender is installed on your system:
```
File "C:\Users\THY\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\core_processes\export_data\blender_stuff\get_best_guess_of_blender_path.py", line 19, in guess_blender_exe_path_from_path
best_guess = blender_folder_paths[-1]
~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```
This looks like a legitimate bug, I'll work on getting a patch through. 

In the mean time, can you open Power Shell and run `Get-Command Blender` and let me know what gets output? That will help see why blender isn't being found.
