### ISSUE TITLE
Blender export fails when triggered from the GUI

### ISSUE THREAD

**Issue by raphCode** [freemocap/freemocap#529]
I noticed that exporting the mocap data to blender from the freemocap GUI does show some activity in the terminal ending with "Blender quit" after several seconds, but no .blend file is created and blender does not open.
The freemocap addon is installed, as can be confirmed by opening blender manually and checking the settings.

I also had a case where the blender addon was processing data ("calculating joint averages and stddev" in the freemocap terminal), and then it hanged indefinitely. This was on windows with a big 7000-frames mocap session.

I can reproduce all of this every time.
Yes, I was too lazy to cleanly record information that would help debugging this, so in this issue I want to confirm if it happens only with my setup or for everyone.

However, what I found to work is to open up blender, activate the freemocap addon and the rigify addon, and then using the feemocap addon to  import the data from within blender. No freemocap GUI or processes are involved here.

I used the freemocap 1.0 release and found this behavior in the following configurations:
- Linux, blender 4.0
- Win10, blender 4.0
- Win10, blender 3.6

**Comment by philipqueen** [comment]
Hello again @raphCode, You're not the only one this happens to. You do need to have the Rigify plugin enabled in Blender for the freemocap export to work correctly. But we are still having problems with that part hanging, or not running from the start as you noticed.
So far, I've always been able to redo the blender export and have it work after a few tries. If you have a recording that always fails and would be willing to share it with us for testing, that would be very appreciated. If you continue to attempt and want to share any logs or other debugging info, that would help too.

**Comment by ralphtheninja** [comment]
I think I might have the same error. Afaict there's some missing function (see log below). I extracted the blender command (currently using locally compiled blender) and ran it separately to see if I could get a callstack:

```
Creating keyframed empty from: left_hand_middle_finger_tip...
Creating keyframed empty from: left_hand_ring_finger_mcp...
Creating keyframed empty from: left_hand_ring_finger_pip...
Creating keyframed empty from: left_hand_ring_finger_dip...
Creating keyframed empty from: left_hand_ring_finger_tip...
Creating keyframed empty from: left_hand_pinky_mcp...
Creating keyframed empty from: left_hand_pinky_pip...
Creating keyframed empty from: left_hand_pinky_dip...
Creating keyframed empty from: left_hand_pinky_tip...
Creating keyframed empty from: center_of_mass...
Finished creating keyframed empties: dict_keys(['body', 'hands', 'other'])
Adding rig...
2024-01-22 15:40:31,364 - root - ERROR - <class 'AttributeError'> Error while creating the rig: Calling operator "bpy.ops.object.armature_human_metarig_add" error, could not be found
Calling operator "bpy.ops.object.armature_human_metarig_add" error, could not be found
Failed to add rig: Calling operator "bpy.ops.object.armature_human_metarig_add" error, could not be found
Calling operator "bpy.ops.object.armature_human_metarig_add" error, could not be found
Traceback (most recent call last):
  File "/home/lms/python/freemocap/freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/ajc_addon/run_simple.py", line 18, in <module>
    run_simple(recording_path_input=recording_path_input, blender_file_save_path_input=blender_file_save_path_input)
  File "/home/lms/python/freemocap/freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/ajc_addon/run_simple.py", line 7, in run_simple
    ajc27_run_as_main_function(recording_path=str(recording_path_input),
  File "/home/lms/.config/blender/4.1/scripts/addons/ajc27_freemocap_blender_addon/run_as_main.py", line 21, in ajc27_run_as_main_function
    controller.run_all()
  File "/home/lms/.config/blender/4.1/scripts/addons/ajc27_freemocap_blender_addon/core_functions/main_controller.py", line 361, in run_all
    self.add_rig()
  File "/home/lms/.config/blender/4.1/scripts/addons/ajc27_freemocap_blender_addon/core_functions/main_controller.py", line 220, in add_rig
    raise e
  File "/home/lms/.config/blender/4.1/scripts/addons/ajc27_freemocap_blender_addon/core_functions/main_controller.py", line 208, in add_rig
    self.rig = add_rig(
               ^^^^^^^^
  File "/home/lms/.config/blender/4.1/scripts/addons/ajc27_freemocap_blender_addon/core_functions/rig/add_rig.py", line 781, in add_rig
    raise e
  File "/home/lms/.config/blender/4.1/scripts/addons/ajc27_freemocap_blender_addon/core_functions/rig/add_rig.py", line 28, in add_rig
    bpy.ops.object.armature_human_metarig_add()
  File "/home/lms/src/blender-git/build_linux/bin/4.1/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.object.armature_human_metarig_add" error, could not be found

Blender quit
```

**Comment by ralphtheninja** [comment]
Enabling the `rigify` plugin in `blender` solved this. Sorry for the noise! (But maybe someone else has the same problem and searches for the same error in the future).
