### ISSUE TITLE
Ubuntu 22.04 build cometic issues, errors, and permission quirks

### ISSUE THREAD

**Issue by Joel-Mckay** [freemocap/freemocap#544]
I ran the demo dataset successfully, but ran into a number of issues others may encounter.  It is absolutely inspiring to see such a fun project in the OSS community, and we dropped a little present for your team into the coffee fund. =)

We eventually did get things to run on Ubuntu 22.04, but found a few quirks with the current git head build.

We should be done our small Camera image sequence tool in a month or two (will help clean up budget cam capture quality a bit, and reduce i/o constrained SSD use for up to nine 1080p 30fps cameras)... still need  pop up a repo, create a short manual,  and ping you guys in case anyone finds such things useful for their own fun.
=) 
Cheers,
J
![axis_err](https://github.com/freemocap/freemocap/assets/2208829/4cf1d779-dcb8-4711-b3fa-a0e51f90f406)
![axis_err2](https://github.com/freemocap/freemocap/assets/2208829/be6d626a-d6dc-4f11-b87a-1262e35c075e)
![button](https://github.com/freemocap/freemocap/assets/2208829/1eff0151-f194-4cf3-ae02-869aaa3de31f)
![OK_classic](https://github.com/freemocap/freemocap/assets/2208829/d0fbe924-b97e-4ba4-9ab3-23521d4ae8b5)

During import:

An error occurs when selecting the synchronize videos checkbox (see very bottom of page). 
However, even under regular user the user will not see any indication on the GUI about slow/long running tasks. Please consider adding a progress bar or spinner+warning message, as the program can't really be packaged for regular users with only the terminal showing  the dataset  processing state.

During task setup:

1. cosmetic issue on gnome... button overlap (see jpg), and git head tree missing image resources
2. errors for missing assets
`
qt.svg: Could not create image from "/home/user/SRC/freemocap/freemocap/assets/logo/16530236.png"
`

During export:

The permission issues arise as freemocap assumes the package path is in the user installation area:

1. associated .blend files with  blender4 snap (as blender3 does not start properly while running freemocap, no idea why.. but likely an OS specific install issue
2. set freemocap to use blender 3 distro package version to export from freemocap 
3. tell users to enable rigify plug-in in blender before attempting export
4. Had to allow access to install /usr/local/lib/python3.10/dist-packages/ajc27_freemocap_blender_addon.zip
sudo chown -R user:user /usr/local/lib/python3.10/dist-packages/
5. ran freemopcap export again to bypass permission weirdness below
6. undo permission tweak
sudo chown -R root:root /usr/local/lib/python3.10/dist-packages/
7. export seems to work now in classic mode, but ajc27_freemocap_blender_addon model axis is flipped (see screen grab)

the export error:
`
024-02-24 07:36:05,025 - freemocap.core_processes.export_data.blender_stuff.export_to_blender.export_to_blender - INFO - Exporting session data to a Blender scene at: /home/user/freemocap_data/recording_sessions/import_synchronized_videos/import_synchronized_videos.blend using Blender executable at /usr/bin/blender
[2024-02-24T07:36:05.025584] [Dt:0.000224s] [    INFO] [freemocap.core_processes.export_data.blender_stuff.export_to_blender.methods.ajc_addon.run_ajc_addon_main] [run_ajc_addon_main:run_ajc_blender_addon_subprocess():40] [PID:31360:MainProcess TID:140104579112960:MainThread ] Running ajc27_freemocap_blender_addon as a subprocess using script at : /usr/local/lib/python3.10/dist-packages/ajc27_freemocap_blender_addon/run_as_main.py
2024-02-24 07:36:05,025 - freemocap.core_processes.export_data.blender_stuff.export_to_blender.methods.ajc_addon.run_ajc_addon_main - INFO - Running ajc27_freemocap_blender_addon as a subprocess using script at : /usr/local/lib/python3.10/dist-packages/ajc27_freemocap_blender_addon/run_as_main.py
Color management: using fallback mode for management
Color management: Error could not find role data role.
Blender 3.0.1
Read prefs: /home/user/.config/blender/3.0/config/userpref.blend
Color management: scene view "Filmic" not found, setting default "Standard".
Running /home/user/SRC/freemocap/freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/ajc_addon/install/bpy_install_addon.py as a subprocess to install the addon...

Installing blender addon named `ajc27_freemocap_blender_addon` from root directory: `/usr/local/lib/python3.10/dist-packages/ajc27_freemocap_blender_addon`

Failed to create zip file at
[Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/ajc27_freemocap_blender_addon.zip'
Traceback (most recent call last):
  File "/home/user/SRC/freemocap/freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/ajc_addon/install/bpy_install_addon.py", line 78, in <module>
    bpy_install_addon(addon_root_directory=addon_root_directory)
  File "/home/user/SRC/freemocap/freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/ajc_addon/install/bpy_install_addon.py", line 44, in bpy_install_addon
    zip_file_path = create_zip_from_folder(addon_folder_path=addon_root_directory)
  File "/home/user/SRC/freemocap/freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/ajc_addon/install/bpy_install_addon.py", line 29, in create_zip_from_folder
    raise e
  File "/home/user/SRC/freemocap/freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/ajc_addon/install/bpy_install_addon.py", line 22, in create_zip_from_folder
    shutil.make_archive(base_name=str(zip_path.with_suffix("")), format="zip", root_dir=tmp_path.parent)
  File "/usr/lib/python3.10/shutil.py", line 1124, in make_archive
    filename = func(base_name, base_dir, **kwargs)
  File "/usr/lib/python3.10/shutil.py", line 983, in _make_zipfile
    with zipfile.ZipFile(zip_filename, "w",
  File "/usr/lib/python3.10/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/ajc27_freemocap_blender_addon.zip'
`

the import error:
`
qt.svg: Could not create image from "/home/user/SRC/freemocap/freemocap/assets/logo/16530236.png"
[2024-02-24T08:02:24.754119] [Dt:103.753519s] [    INFO] [freemocap.gui.qt.main_window.freemocap_main_window] [freemocap_main_window:open_import_videos_dialog():471] [PID:10742:MainProcess TID:139984944881664:MainThread ] Opening `Import Videos` dialog... 
2024-02-24 08:02:24,754 - freemocap.gui.qt.main_window.freemocap_main_window - INFO - Opening `Import Videos` dialog... 
[2024-02-24T08:02:51.727234] [Dt:26.987689s] [    INFO] [freemocap.gui.qt.widgets.import_videos_wizard] [import_videos_wizard:_handle_synchronize_checkbox_toggled():191] [PID:10742:MainProcess TID:139984944881664:MainThread ] Synchronize videos selected, videos will be synchronized before importing
2024-02-24 08:02:51,727 - freemocap.gui.qt.widgets.import_videos_wizard - INFO - Synchronize videos selected, videos will be synchronized before importing
[2024-02-24T08:03:02.649014] [Dt:11.308981s] [    INFO] [freemocap.gui.qt.workers.synchronize_videos_thread_worker] [synchronize_videos_thread_worker:__init__():24] [PID:10742:MainProcess TID:139984944881664:MainThread ] Initializing Synchronize Videos Thread Worker
2024-02-24 08:03:02,649 - freemocap.gui.qt.workers.synchronize_videos_thread_worker - INFO - Initializing Synchronize Videos Thread Worker
[2024-02-24T08:03:03.072124] [Dt:0.025781s] [    INFO] [freemocap.gui.qt.workers.synchronize_videos_thread_worker] [synchronize_videos_thread_worker:run():43] [PID:10742:MainProcess TID:139975485523520:Dummy-4 ] Beginning to synchronize videos
2024-02-24 08:03:03,072 - freemocap.gui.qt.workers.synchronize_videos_thread_worker - INFO - Beginning to synchronize videos
[2024-02-24T08:03:03.081936] [Dt:0.004011s] [    INFO] [freemocap.gui.qt.workers.synchronize_videos_thread_worker] [synchronize_videos_thread_worker:run():48] [PID:10742:MainProcess TID:139975485523520:Dummy-4 ] Beginning to synchronize videos to folder /home/user/freemocap_data/recording_sessions/import_synchronized_videos/synchronized_videos
2024-02-24 08:03:03,081 - freemocap.gui.qt.workers.synchronize_videos_thread_worker - INFO - Beginning to synchronize videos to folder /home/user/freemocap_data/recording_sessions/import_synchronized_videos/synchronized_videos
[2024-02-24T08:03:04.001245] [Dt:0.930963s] [    INFO] [root] [get_video_files:get_video_file_list():20] [PID:10742:MainProcess TID:139975485523520:Dummy-4 ] 3 videos found in folder
2024-02-24 08:03:04,001 - root - INFO - 3 videos found in folder
[2024-02-24T08:03:04.052436] [Dt:0.039711s] [    INFO] [root] [path_handling_utilities:create_directory():16] [PID:10742:MainProcess TID:139975485523520:Dummy-4 ] Created directory: /home/user/freemocap_data/recording_sessions/import_synchronized_videos/synchronized_videos/audio_files
2024-02-24 08:03:04,052 - root - INFO - Created directory: /home/user/freemocap_data/recording_sessions/import_synchronized_videos/synchronized_videos/audio_files
[2024-02-24T08:03:06.125008] [Dt:2.380731s] [   ERROR] [freemocap.gui.qt.workers.synchronize_videos_thread_worker] [synchronize_videos_thread_worker:run():66] [PID:10742:MainProcess TID:139975485523520:Dummy-4 ] Something went wrong while synchronizing videos
Traceback (most recent call last):
  File "/home/user/SRC/freemocap/freemocap/gui/qt/workers/synchronize_videos_thread_worker.py", line 50, in run
    self.output_folder_path = synchronize_videos_from_audio(
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/skelly_synchronize.py", line 89, in synchronize_videos_from_audio
    audio_sample_rates = get_audio_sample_rates(video_info_dict=video_info_dict)
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/audio_utilities.py", line 17, in get_audio_sample_rates
    audio_sample_rate_list = [
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/audio_utilities.py", line 18, in <listcomp>
    extract_audio_sample_rate_ffmpeg(file_pathstring=video_dict["video pathstring"])
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/video_functions/ffmpeg_functions.py", line 100, in extract_audio_sample_rate_ffmpeg
    audio_sample_rate = float(cleaned_stdout)
ValueError: could not convert string to float: ''
2024-02-24 08:03:06,125 - freemocap.gui.qt.workers.synchronize_videos_thread_worker - ERROR - Something went wrong while synchronizing videos
Traceback (most recent call last):
  File "/home/user/SRC/freemocap/freemocap/gui/qt/workers/synchronize_videos_thread_worker.py", line 50, in run
    self.output_folder_path = synchronize_videos_from_audio(
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/skelly_synchronize.py", line 89, in synchronize_videos_from_audio
    audio_sample_rates = get_audio_sample_rates(video_info_dict=video_info_dict)
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/audio_utilities.py", line 17, in get_audio_sample_rates
    audio_sample_rate_list = [
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/audio_utilities.py", line 18, in <listcomp>
    extract_audio_sample_rate_ffmpeg(file_pathstring=video_dict["video pathstring"])
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/video_functions/ffmpeg_functions.py", line 100, in extract_audio_sample_rate_ffmpeg
    audio_sample_rate = float(cleaned_stdout)
ValueError: could not convert string to float: ''
[2024-02-24T08:03:06.468847] [Dt:0.037815s] [   ERROR] [freemocap.gui.qt.workers.synchronize_videos_thread_worker] [synchronize_videos_thread_worker:run():67] [PID:10742:MainProcess TID:139975485523520:Dummy-4 ] could not convert string to float: ''
Traceback (most recent call last):
  File "/home/user/SRC/freemocap/freemocap/gui/qt/workers/synchronize_videos_thread_worker.py", line 50, in run
    self.output_folder_path = synchronize_videos_from_audio(
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/skelly_synchronize.py", line 89, in synchronize_videos_from_audio
    audio_sample_rates = get_audio_sample_rates(video_info_dict=video_info_dict)
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/audio_utilities.py", line 17, in get_audio_sample_rates
    audio_sample_rate_list = [
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/audio_utilities.py", line 18, in <listcomp>
    extract_audio_sample_rate_ffmpeg(file_pathstring=video_dict["video pathstring"])
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/video_functions/ffmpeg_functions.py", line 100, in extract_audio_sample_rate_ffmpeg
    audio_sample_rate = float(cleaned_stdout)
ValueError: could not convert string to float: ''
2024-02-24 08:03:06,468 - freemocap.gui.qt.workers.synchronize_videos_thread_worker - ERROR - could not convert string to float: ''
Traceback (most recent call last):
  File "/home/user/SRC/freemocap/freemocap/gui/qt/workers/synchronize_videos_thread_worker.py", line 50, in run
    self.output_folder_path = synchronize_videos_from_audio(
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/skelly_synchronize.py", line 89, in synchronize_videos_from_audio
    audio_sample_rates = get_audio_sample_rates(video_info_dict=video_info_dict)
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/audio_utilities.py", line 17, in get_audio_sample_rates
    audio_sample_rate_list = [
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/audio_utilities.py", line 18, in <listcomp>
    extract_audio_sample_rate_ffmpeg(file_pathstring=video_dict["video pathstring"])
  File "/usr/local/lib/python3.10/dist-packages/skelly_synchronize/core_processes/video_functions/ffmpeg_functions.py", line 100, in extract_audio_sample_rate_ffmpeg
    audio_sample_rate = float(cleaned_stdout)
ValueError: could not convert string to float: ''
[2024-02-24T08:03:06.471557] [Dt:0.009844s] [    INFO] [freemocap.gui.qt.workers.synchronize_videos_thread_worker] [synchronize_videos_thread_worker:run():72] [PID:10742:MainProcess TID:139975485523520:Dummy-4 ] Synchronizing Videos Complete
2024-02-24 08:03:06,471 - freemocap.gui.qt.workers.synchronize_videos_thread_worker - INFO - Synchronizing Videos Complete
Traceback (most recent call last):
  File "/home/user/SRC/freemocap/freemocap/gui/qt/widgets/import_videos_wizard.py", line 211, in _handle_video_synchronization_finished
    for path in get_video_paths(path_to_video_folder=self.synchronize_videos_thread_worker.output_folder_path)
  File "/home/user/SRC/freemocap/freemocap/utilities/get_video_paths.py", line 8, in get_video_paths
    list_of_video_paths = list(Path(path_to_video_folder).glob("*.mp4")) + list(
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/user/SRC/freemocap/freemocap/gui/qt/widgets/import_videos_wizard.py", line 211, in _handle_video_synchronization_finished
    for path in get_video_paths(path_to_video_folder=self.synchronize_videos_thread_worker.output_folder_path)
  File "/home/user/SRC/freemocap/freemocap/utilities/get_video_paths.py", line 8, in get_video_paths
    list_of_video_paths = list(Path(path_to_video_folder).glob("*.mp4")) + list(
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Comment by philipqueen** [comment]
Hey thanks for the feedback, and the coffee!

We've fixed the progress feedback issue already, there will be in-GUI progress updates in the next release (coming soon!).

I'll look into that synchronizing error - were you able to get your videos synchronized?

I'll look into the GUI rendering issue, but for the permissions, do you have ideas on how to fix it so root access isn't required? I'm not very clear on what you mean by "freemocap assumes the package path is in the user installation area". I just don't know linux well enough to see what causes this/how it would be fixed.

**Comment by Joel-Mckay** [comment]
Indeed, the sample mp4 are without an audio track, and our image sequence source are also not audio keyed. We don't plan on using the feature (the network cameras have limited CPU power), but a sudden image luminance histogram peak shift should be robust enough for detecting sudden flashes or video cuts (I assume this is how the second method was implemented).

Q: "do you have ideas on how to fix it so root access isn't required"

A: I'd just check if the OS is Linux with a "uname" call result, and then check if the included lib path owner is "root".  If the check indicates a OS package installation method was used (i.e. like python3-somelib.deb for all users etc.), than force the additional side-loaded pip install into the local user scope path for python.  

Probably more robust to use the pip install path information, but if the selected active python version is the same this may work:
`
echo "$HOME/.local/lib/python$(python -V | grep -Po -m 1 '[0-9]+\.[0-9]+')/site-packages"
`
The program could assume this user path exists if pip already installed lib dependencies into this local user path, and the python interpreter is the same version. 

Cheers, =)
J

**Comment by philipqueen** [comment]
Yep, the lack of audio would explain the synchronization issue. You're right that the other method looks for a sudden flash visible to all cameras. You can use that to synchronize, or import already synchronized videos (each video must be the exact number of frames). I've added better error handling for the no audio case to my to do list though.

And thanks for filling in the details on the linux permissions!
