### ISSUE TITLE
Error with the virtual marker pydantic model validation

### ISSUE THREAD

**Issue by aaroncherian** [freemocap/freemocap#577]
In the `get_model_data_from_skellytracker` branch, there's an issue with the virtual marker validator:

```
class VirtualMarkerInfo(BaseModel):
    virtual_markers: Dict[str, Dict[str, List[Union[str, int, float]]]]

    @validator("virtual_markers", each_item=True)
    def validate_virtual_marker(cls, virtual_marker: Dict[str, List[Union[str, int, float]]]):
        marker_names = virtual_marker.get("marker_names", [])
        marker_weights = virtual_marker.get("marker_weights", [])

        if len(marker_names) != len(marker_weights):
            raise ValueError(
                f"The number of marker names must match the number of marker weights for {virtual_marker}. Currently there are {len(marker_names)} names and {len(marker_weights)} weights."
            )

        if not isinstance(marker_names, list) or not all(isinstance(name, str) for name in marker_names):
            raise ValueError(f"Marker names must be a list of strings for {marker_names}.")

        if not isinstance(marker_weights, list) or not all(
            isinstance(weight, (int, float)) for weight in marker_weights
        ):
            raise ValueError(f"Marker weights must be a list of numbers for {virtual_marker}.")

        weight_sum = sum(marker_weights)
        if not 0.99 <= weight_sum <= 1.01:  # Allowing a tiny bit of floating-point leniency
            raise ValueError(
                f"Marker weights must sum to approximately 1 for {virtual_marker} Current sum is {weight_sum}."
            )

        return virtual_marker
```

Specifically the type hinting of `Dict[str, Dict[str, List[Union[str, int, float]]]]`

There's weird validation things happening where I was getting this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for VirtualMarkerInfo
virtual_markers -> head_center
  Marker weights must be a list of numbers for {'marker_names': ['left_ear', 'right_ear'], 'marker_weights': ['0.5', '0.5']}. (type=value_error)
virtual_markers -> neck_center
  Marker weights must be a list of numbers for {'marker_names': ['left_shoulder', 'right_shoulder'], 'marker_weights': ['0.5', '0.5']}. (type=value_error)
virtual_markers -> trunk_center
  Marker weights must be a list of numbers for {'marker_names': ['left_shoulder', 'right_shoulder', 'left_hip', 'right_hip'], 'marker_weights': ['0.25', '0.25', '0.25', '0.25']}. (type=value_error)
virtual_markers -> hips_center
  Marker weights must be a list of numbers for {'marker_names': ['left_hip', 'right_hip'], 'marker_weights': ['0.5', '0.5']}. (type=value_error)
  ```
  
  As you can see, all the weights are coming in as `strings`, even though in the model info/dictionary they're `floats`. Specifically, this line seems to be the culprit:
  
  ` virtual_markers: Dict[str, Dict[str, List[Union[str, int, float]]]]`
  
 What it seems to be is that it actually converts the marker weights into a `string`. If I took out the `str` type hint, and just left `int` and `float`, it converted all the weights to the nearest `int` (which we definitely do not want to do). 
 
 
 I'm going to change it back to the way it was to get it working, but making a note of this here

**Comment by philipqueen** [comment]
Interesting. Can you check if it changes the behavior if you do `List[Union[float, int, str]]`? I'm not familiar with how pydantic handles Union types - I assumed it would be "closest match" but that isn't correct.

Maybe the `Dict[str, List[Union[str, int, float]]` does need to be its own model to get finer control of the types

**Comment by aaroncherian** [comment]
How I'm understanding it is that when we have something like this:

```
class VirtualMarkerInfo(BaseModel):
    virtual_markers: Dict[str, Dict[str, List[Union[str, int, float]]]]
```

The model does 2 things - it first checks (in order of what's written), whether the type matches, and if it doesn't, and it is possible to convert the type, it will convert to the specified type. So in this case, it looked at all of the entry `floats`, and saw that they weren't `strings`, and then tried to convert them all to `strings`. If it couldn't convert them all to strings, it would have moved on to trying it with the `int` and so on.

So in our case, we would either just want it to be a `Dict[str, List]`, and use the existing validation methods to check that it is a `float`, or we would want to do `Dict[str, List[float]` or something like that. But I don't think we want `strings` as an option here, because of the conversion aspect.

**Comment by philipqueen** [comment]
> But I don't think we want `strings` as an option here, because of the conversion aspect.

We need the string flag because of the marker names list. But it seems like declaring it as `Union[float, str]` should fix the issue.
```
    virtual_markers_definitions = {
        "head_center": {
            "marker_names": ["left_ear", "right_ear"],
            "marker_weights": [0.5, 0.5],
        }, ...
}
```

**Comment by aaroncherian** [comment]
That would fix the issue - but the underlying logic of how `Union[float,str]` (I looked into it a bit more) works is that the pydantic model will take both, but it prefers the first if possible. So when we have that what we're saying is 'we'll take floats and strings, but we prefer floats', not 'we have one type in this dictionary that needs strings and another that needs floats'.
