### ISSUE TITLE
mediapipe issue

### ISSUE THREAD

**Issue by ariyan1403** [freemocap/freemocap#600]
hi everybody , 

I installed all the steps successfully, but when running the freemocap, it shows this error in the console. Can anyone guide me?

thankyou verymuch .... 

1- python 3.11
2- pip install freemocap (all package successfully installed )
3- freemocap 

but EROR....

[Errno 2] No such file or directory: 'C:\\Users\\artSEO\\freemocap_data\\logs_info_and_settings\\gui_state.json'
←[96m[2024-05-16T03:41:42.963373] [Δt:0.000000s] [    INFO] [freemocap] [__init__:<module>():18] [←[38;2;50;50;172mPID:8364:MainProcess←[0m ←[38;2;50;50;255mTID:2144:MainThread←[0m ] Initializing freemocap package, version: v1.2.2, from file: C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\__init__.py←[0m
Thank you for using skelly_viewer!
This is printing from: C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\skelly_viewer\__init__.py
Source code for this package is available at: https://github.com/freemocap/skelly_viewer/
←[96m[2024-05-16T03:41:47.743234] [Δt:4.779861s] [    INFO] [skelly_viewer.config.logging_configuration] [logging_configuration:configure_logging():43] [←[38;2;50;50;172mPID:8364:MainProcess←[0m ←[38;2;50;50;255mTID:2144:MainThread←[0m ] Logging already configured!←[0m
adding base_package_path: C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellycam : to sys.path
Setting up skellycam logging C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellycam\system\log_config\logsetup.py
←[96m[2024-05-16T03:41:47.756226] [Δt:0.014992s] [    INFO] [skellycam.system.log_config.logsetup] [logsetup:configure_logging():42] [←[38;2;50;50;172mPID:8364:MainProcess←[0m ←[38;2;50;50;255mTID:2144:MainThread←[0m ] Logging already configured!←[0m
←[96m[2024-05-16T03:41:47.758227] [Δt:0.000000s] [    INFO] [skellycam] [__init__:<module>():27] [←[38;2;50;50;172mPID:8364:MainProcess←[0m ←[38;2;50;50;255mTID:2144:MainThread←[0m ] Initializing skellycam package, version: v2023.12.1090, from file: C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellycam\__init__.py←[0m
Thank you for using skellytracker!
This is printing from: C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellytracker\__init__.py
Source code for this package is available at: https://github.com/freemocap/skellytracker
adding base_package_path: C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellytracker : to sys.path
To use mediapipe_holistic_tracker, install skellytracker[mediapipe]
To use yolo_mediapipe_combo_tracker, install skellytracker[mediapipe, yolo] or skellytracker[all]
[2024-05-16T03:42:12.255960] [Δt:24.497733s] [    INFO] [skellytracker.system.logging_configuration] [logging_configuration:configure_logging():43] [PID:8364:MainProcess TID:2144:MainThread ] Logging already configured!
adding base_package_path: C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages : to sys.path
Traceback (most recent call last):
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\__main__.py", line 8, in <module>
    from freemocap.gui.qt.freemocap_main import qt_gui_main
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\freemocap_main.py", line 10, in <module>
    from freemocap.gui.qt.main_window.freemocap_main_window import MainWindow, EXIT_CODE_REBOOT
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\main_window\freemocap_main_window.py", line 28, in <module>
    from freemocap.data_layer.recording_models.post_processing_parameter_models import (
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\data_layer\recording_models\post_processing_parameter_models.py", line 4, in <module>
    from skellytracker.trackers.mediapipe_tracker.mediapipe_model_info import (
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellytracker\trackers\mediapipe_tracker\mediapipe_model_info.py", line 2, in <module>
    from mediapipe.python.solutions import holistic as mp_holistic
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\mediapipe\__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed while importing _framework_bindings: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Scripts\freemocap.exe\__main__.py", line 4, in <module>

    ^
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\__main__.py", line 13, in <module>
    from freemocap.gui.qt.freemocap_main import qt_gui_main
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\freemocap_main.py", line 10, in <module>
    from freemocap.gui.qt.main_window.freemocap_main_window import MainWindow, EXIT_CODE_REBOOT
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\gui\qt\main_window\freemocap_main_window.py", line 28, in <module>
    from freemocap.data_layer.recording_models.post_processing_parameter_models import (
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\freemocap\data_layer\recording_models\post_processing_parameter_models.py", line 4, in <module>
    from skellytracker.trackers.mediapipe_tracker.mediapipe_model_info import (
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\skellytracker\trackers\mediapipe_tracker\mediapipe_model_info.py", line 2, in <module>
    from mediapipe.python.solutions import holistic as mp_holistic
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\mediapipe\__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "C:\Users\artSEO\AppData\Local\Programs\Python\Python311\Lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed while importing _framework_bindings: %1 is not a valid Win32 application.

**Comment by philipqueen** [comment]
Hi @ariyan1403, it appears there's something wrong with your mediapipe installation.
In your python environment, try running `pip uninstall mediapipe` followed by `pip install mediapipe==0.10.9` and make sure there are no errors reported.

Also, if you're not already using a separate environment for freemocap I recommend that.

**Comment by philipqueen** [comment]
>  but the speed running is very low

Interesting, is it the mediapipe itself that is running slowly or something else? For mediapipe, you can change how many processes it's running between to optimize it for your system.

**Comment by takeraparterer** [comment]
> Hi [@ariyan1403](https://github.com/ariyan1403), it appears there's something wrong with your mediapipe installation. In your python environment, try running `pip uninstall mediapipe` followed by `pip install mediapipe==0.10.9` and make sure there are no errors reported.
> 
> Also, if you're not already using a separate environment for freemocap I recommend that.

I can't install that version

**Comment by caadhavan-lang** [comment]
I followed

this steps 👍 1. Create a Python environment (python3.12 recommended)
2. Enter command: pip install freemocap
3. Enter command: freemocap

when I typed freemocap 

the error occurring
 
plz help me 


xTraceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/freemocap/__main__.py", line 8, in <module>
    from freemocap.gui.qt.freemocap_main import qt_gui_main
  File "/opt/anaconda3/lib/python3.13/site-packages/freemocap/gui/qt/freemocap_main.py", line 9, in <module>
    from freemocap.gui.qt.main_window.freemocap_main_window import MainWindow, EXIT_CODE_REBOOT
  File "/opt/anaconda3/lib/python3.13/site-packages/freemocap/gui/qt/main_window/freemocap_main_window.py", line 24, in <module>
    from freemocap.core_processes.export_data.blender_stuff.export_to_blender.export_to_blender import export_to_blender
  File "/opt/anaconda3/lib/python3.13/site-packages/freemocap/core_processes/export_data/blender_stuff/export_to_blender/export_to_blender.py", line 11, in <module>
    from freemocap.core_processes.export_data.blender_stuff.export_to_blender.methods.legacy.run_megascript_take2 import \
        run_blender_megascript_take2
  File "/opt/anaconda3/lib/python3.13/site-packages/freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/legacy/run_megascript_take2.py", line 10, in <module>
    from freemocap.core_processes.detecting_things_in_2d_images.mediapipe_stuff.data_models.mediapipe_skeleton_names_and_connections import (
        mediapipe_names_and_connections_dict,
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/freemocap/core_processes/detecting_things_in_2d_images/mediapipe_stuff/data_models/mediapipe_skeleton_names_and_connections.py", line 1, in <module>
    from mediapipe.python.solutions import holistic as mp_holistic
ModuleNotFoundError: No module named 'mediapipe.python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/freemocap", line 3, in <module>
