### ISSUE TITLE
 module 'cv2' has no attribute 'VideoCapture'

### ISSUE THREAD

**Issue by nickreal03** [freemocap/freemocap#605]
After a fresh install of everything... I get the following issue. (This happen after it tried to patch something when the UI opened for the first time) After that I get all this and nothing working.

(freemocap-env) C:\Users\tomas\freemocap>python -m freemocap
[Errno 2] No such file or directory: 'C:\\Users\\tomas\\freemocap_data\\logs_info_and_settings\\gui_state.json'
[2024-05-23T00:32:57.222393] [Δt:0.000500s] [    INFO] [freemocap] [__init__:<module>():18] [PID:9956:MainProcess TID:10588:MainThread ] Initializing freemocap package, version: v1.2.2, from file: C:\Users\tomas\freemocap\freemocap\__init__.py
Thank you for using skelly_viewer!
This is printing from: D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skelly_viewer\__init__.py
Source code for this package is available at: https://github.com/freemocap/skelly_viewer/
[2024-05-23T00:32:58.219687] [Δt:0.996793s] [    INFO] [skelly_viewer.config.logging_configuration] [logging_configuration:configure_logging():43] [PID:9956:MainProcess TID:10588:MainThread ] Logging already configured!
adding base_package_path: D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam : to sys.path
Setting up skellycam logging D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\system\log_config\logsetup.py
[2024-05-23T00:32:58.225692] [Δt:0.007016s] [    INFO] [skellycam.system.log_config.logsetup] [logsetup:configure_logging():42] [PID:9956:MainProcess TID:10588:MainThread ] Logging already configured!
[2024-05-23T00:32:58.227190] [Δt:0.000487s] [    INFO] [skellycam] [__init__:<module>():27] [PID:9956:MainProcess TID:10588:MainThread ] Initializing skellycam package, version: v2023.12.1090, from file: D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\__init__.py
adding base_package_path: C:\Users\tomas\freemocap : to sys.path
adding base_package_path: D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam : to sys.path
Setting up skellycam logging D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\system\log_config\logsetup.py
[2024-05-23T00:32:58.278687] [Δt:0.051498s] [    INFO] [skellycam.system.log_config.logsetup] [logsetup:configure_logging():42] [PID:9956:MainProcess TID:10588:MainThread ] Logging already configured!
[2024-05-23T00:32:58.278687] [Δt:0.000000s] [    INFO] [skellycam] [__init__:<module>():27] [PID:9956:MainProcess TID:10588:MainThread ] Initializing skellycam package, version: v2023.12.1090, from file: D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\__init__.py
Traceback (most recent call last):
  File "C:\Users\tomas\freemocap\freemocap\__main__.py", line 8, in <module>
    from freemocap.gui.qt.freemocap_main import qt_gui_main
  File "C:\Users\tomas\freemocap\freemocap\gui\qt\freemocap_main.py", line 10, in <module>
    from freemocap.gui.qt.main_window.freemocap_main_window import MainWindow, EXIT_CODE_REBOOT
  File "C:\Users\tomas\freemocap\freemocap\gui\qt\main_window\freemocap_main_window.py", line 18, in <module>
    from skellycam import (
  File "D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\__init__.py", line 29, in <module>
    from skellycam.opencv.camera.camera import Camera
  File "D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\opencv\camera\camera.py", line 9, in <module>
    from skellycam.opencv.camera.internal_camera_thread import VideoCaptureThread
  File "D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\opencv\camera\internal_camera_thread.py", line 11, in <module>
    from skellycam.opencv.config.apply_config import apply_configuration
  File "D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\opencv\config\apply_config.py", line 11, in <module>
    def apply_configuration(cv2_vid_cap: cv2.VideoCapture, config: CameraConfig):
                                         ^^^^^^^^^^^^^^^^
AttributeError: module 'cv2' has no attribute 'VideoCapture'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tomas\freemocap\freemocap\__main__.py", line 13, in <module>
    from freemocap.gui.qt.freemocap_main import qt_gui_main
  File "C:\Users\tomas\freemocap\freemocap\gui\qt\freemocap_main.py", line 10, in <module>
    from freemocap.gui.qt.main_window.freemocap_main_window import MainWindow, EXIT_CODE_REBOOT
  File "C:\Users\tomas\freemocap\freemocap\gui\qt\main_window\freemocap_main_window.py", line 18, in <module>
    from skellycam import (
  File "D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\__init__.py", line 29, in <module>
    from skellycam.opencv.camera.camera import Camera
  File "D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\opencv\camera\camera.py", line 9, in <module>
    from skellycam.opencv.camera.internal_camera_thread import VideoCaptureThread
  File "D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\opencv\camera\internal_camera_thread.py", line 11, in <module>
    from skellycam.opencv.config.apply_config import apply_configuration
  File "D:\Users\tomas\miniconda3\envs\freemocap-env\Lib\site-packages\skellycam\opencv\config\apply_config.py", line 11, in <module>
    def apply_configuration(cv2_vid_cap: cv2.VideoCapture, config: CameraConfig):
                                         ^^^^^^^^^^^^^^^^
AttributeError: module 'cv2' has no attribute 'VideoCapture'

**Comment by philipqueen** [comment]
Hi, it appears something went wrong in fixing the opencv conflict.

To fix it, close Freemocap and run `pip uninstall opencv-python opencv-contrib-python` followed by `pip install opencv-contrib-python==4.8.1.78`. Then restart Freemocap.

**Comment by nickreal03** [comment]
> ... pip install opencv-contrib-python==4.8.1.78

Yup that worked! Thanks allot... now for the real testing...

Thanks again!
